apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: app1
     namespace: api
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: app1
     template:
       metadata:
         labels:
           app: app1
       spec:
         containers:
         - name: app1-container
           image: nginx
           ports:
           - containerPort: 80
           - containerPort: 443
           envFrom:
           - configMapRef:
               name: app-config
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: app1
     namespace: api
   spec:
     ports:
     - port: 80
       targetPort: 80
       protocol: TCP
     - port: 443
       targetPort: 443
       protocol: TCP
     selector:
       app: app1
