   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: api-ingress
     namespace: api
     annotations:
       nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Установлено в false, чтобы отключить обязательный HTTPS, что упрощает развертывание на локальном компьютере.
       nginx.ingress.kubernetes.io/rewrite-target: /  
   spec:
     rules:
     - host: localhost
       http:
         paths:
         - path: /app1
           pathType: Prefix
           backend:
             service:
               name: app1
               port:
                 number: 80
         - path: /app2
           pathType: Prefix
           backend:
             service:
               name: app2
               port:
                 number: 80
